server:
  port: 8083
spring:
  application:
    name: ms-account
  cloud:
    config:
      name: ms-account
      discovery:
        enabled: true
        service-id: ms-config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: https://bootcamp-ms-eureka-server-g3.azurewebsites.net:443/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"