server:
  port: 9082
spring:
  application:
    name: ms-customer
  cloud:
    config:
      name: ms-customer
      discovery:
        enabled: true
        service-id: ms-config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://ms-eureka-server:8761/eureka/
owner:
  name: Diane

management:
  endpoints:
    web:
      exposure:
        include: "*"