server:
  port: 9084
spring:
  application:
    name: ms-cards
  cloud:
    config:
      name: ms-cards
      discovery:
        enabled: true
        service-id: ms-config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ms-eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"