server:
  port: 443
spring:
  application:
    name: ms-eureka-server
  cloud:
    config:
      discovery:
        service-id: ms-config-server
eureka:
  renewalPercenThreshold: 0.85
  instance:
    hostname: bootcamp-ms-eureka-server-g3.azurewebsites.net
  client:
    serviceUrl:
      defaultZone: https://bootcamp-ms-eureka-server-g3.azurewebsites.net:443/eureka
    registerWithEureka: false
    fetchRegistry: false