server:
  port: 8761
spring:
  application:
    name: ms-eureka-server
  cloud:
    config:
      discovery:
        service-id: ms-config-server
eureka:
  renewalPercenThreshold: 0.85
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false