server:
  port: 9086
spring:
  application:
    name: ms-transactions
  cloud:
    config:
      name: ms-transactions
      discovery:
        enabled: true
        service-id: ms-config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ms-eureka-server:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"